import '../styles/tailwind.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { type ReactNode } from 'react'

import Providers from '@/lib/utils/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => (
	<html lang='en'>
		<body className={inter.className}>
			<Providers>{children}</Providers>
		</body>
	</html>
)

export default RootLayout
